{
 "title": "Netology 10.3",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "File system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "CPU LA 1 5 15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(node_cpu_seconds_total{job=\"nodeexporter\"}[1m]))",
     "legendFormat": "1"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{job=\"nodeexporter\"}[5m]))",
     "legendFormat": "5"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{job=\"nodeexporter\"}[15m]))",
     "legendFormat": "15"
    }
   ]
  },
  {
   "title": "Mem free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "MemFree" }
   ]
  },
  {
   "title": "100% idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "idle percent"
    }
   ]
  }
 ]
}