apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deployment2
  labels:
    app: depl2
spec:
  selector:
    matchLabels:
      app: depl2
  template:
    metadata:
      labels:
        app: depl2
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: varlog
          mountPath: /output
        ports:
        ports:
        - containerPort: 80
        env:
        - name: HTTP_PORT
          value: "80"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log