
FROM centos:7

RUN yum -y install sudo wget perl-Digest-SHA

COPY elasticsearch-8.5.3-linux-x86_64.tar.gz elasticsearch-8.5.3-linux-x86_64.tar.gz

RUN tar -xzf elasticsearch-8.5.3-linux-x86_64.tar.gz

RUN rm -f elasticsearch-8.5.3-linux-x86_64.tar.gz

RUN echo "cluster.name: cluster_netology_test" >> /elasticsearch-8.5.3/config/elasticsearch.yml && \
    echo "node.name: netology_test" >> /elasticsearch-8.5.3/config/elasticsearch.yml && \
    echo "path.data: /var/lib/elasticsearch" >> /elasticsearch-8.5.3/config/elasticsearch.yml && \
    echo "network.host: 0.0.0.0" >> /elasticsearch-8.5.3/config/elasticsearch.yml && \
    echo "discovery.type: single-node" >> /elasticsearch-8.5.3/config/elasticsearch.yml && \
    echo "xpack.security.enabled: false" >> /elasticsearch-8.5.3/config/elasticsearch.yml

RUN useradd -MU elastic && \
    chown -R elastic:elastic elasticsearch-8.5.3 && \
    mkdir /var/lib/elasticsearch && \
    chown -R elastic:elastic /var/lib/elasticsearch

EXPOSE 9200
EXPOSE 9300

CMD ["sudo", "-u", "elastic", "/elasticsearch-8.5.3/bin/elasticsearch"]



