---

- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - ansible-clickhouse

- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - lighthouse-role

- name: Install Vector
  hosts: vector
  roles: 
    - vector-role
