---
apiVersion: v1
kind: Service
metadata:
  name: multitool-svc
spec:
  selector:
    app: multitool
  ports:
  - name: nginx80
    port: 80
    targetPort: 80
  - name: multitool8080
    port: 8080
    targetPort: 8080