build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo "${CI_DOCKER_CONFIG}" > /kaniko/.docker/config.json
    - >
      export TAG=$(if [[ "$CI_COMMIT_TAG"} ]]; then
                      echo ${CI_COMMIT_TAG};
                   else
                      echo ${CI_COMMIT_SHORT_SHA};
                   fi);
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${CI_REGISTRY}/myapp:${TAG}"
    - echo $TAG
deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  script:
    - sed -i "s/__VERSION__/$CI_COMMIT_TAG/" myappdepl.yaml
    - kubectl get pod
    - kubectl apply -f myappdepl.yaml
  only:
    - tags