---
  - name: clickhouse-role
    src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    version: "1.11.0"
  - name: lighthouse-role
    src: https://github.com/OlegDy/lighthouse-role.git
    version: "1.0.0"
  - name: vector-role
    src: https://github.com/OlegDy/vector-role.git
    version: "1.0.0"


